### PR TITLE
Regression: allow defining neutrinorc as directory

### LINKED ISSUE #370: Allow .neutrinorc.js to be a directory
Right now we do a file-exists check on `.neutrinorc.js` to make sure we have the file before requiring it, but this prevents it from being a directory, which can be nice sometimes when you want to split it up into multiple files.

Just need to switch this check to be non-file-specific.

### PR DESCRIPTION
**Pull request by eliperelman**
Fixes #370.

### CODE REVIEW

File: packages/neutrino/src/utils.js [hunk 1]
```diff
@@ -11,6 +11,16 @@ const createPaths = curry((root, moduleId) => List.of(
   moduleId
 ));
 
+// hasRc :: (String -> String) -> Boolean
```
Comment (helfi92) [inline packages/neutrino/src/utils.js]: // `exists :: ...`

Comment (eliperelman) [reply packages/neutrino/src/utils.js]: lol oops
