### PR TITLE
fix(Jest): Fix Jest middleware always exit with zero code

### LINKED ISSUE #632: neutrino test always exits with 0
When using Jest preset, even if my test suit fails the exit code is always 0 which causes CI to always pass. 

neutrino version 7.2.1+ (also tested on 7.4.0)

It works as expected on v6.2.0

### PR DESCRIPTION
**Pull request by okonet**
Closes #632

Since this regression was introduced in v7, I think it should be released as a patch release in v7 and v8 accordingly.

After spending ~30 mins trying to write tests with Ava I gave up and offering my help with #635

### CODE REVIEW

**Comment by eliperelman** [comment]
Strange, the test for this failed in travis, even though jest says the test passed.

**Comment by okonet** [comment]
Very strange, indeed. I've looked at Jest's results Object and it's says it's all good. Not sure where the 1 code is coming from. For some reason I also see the error code printed twice:

```

0
  ✔ cli_test › @neutrinojs/react (10.1s)
1
0
  ✖ cli_test › @neutrinojs/react + @neutrinojs/jest Failed to test project:

```

when adding a `console.log` here https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/create-project/test/cli_test.js#L28

**Comment by okonet** [comment]
My assumption is that it was passing before since the Jest would never reject.

File: packages/jest/src/index.js [hunk 1]
```diff
@@ -118,10 +118,9 @@ module.exports = (neutrino, opts = {}) => {
 
       writeFileSync(configFile, `${JSON.stringify(options, null, 2)}\n`);
 
-      jest.runCLI(cliOptions, options.roots || [options.rootDir], result =>
-        (result.numFailedTests || result.numFailedTestSuites ?
-          reject() :
-          resolve()));
+      jest.runCLI(cliOptions, options.roots || [options.rootDir])
```
Comment (eliperelman) [inline packages/jest/src/index.js]: I was just thinking, since we are no longer using a callback here, we can remove the `return new Promise` on L99 and instead just return the `runCLI` call, right?

```js
return jest.runCLI(cliOptions, options.roots || [options.rootDir]);
```

Do we even then need to capture `results.success`, or will jest reject if `success` is false?

Comment (okonet) [reply packages/jest/src/index.js]: It won't reject as far as I can say by looking at their code. I think their promise is for some unexpected inside a `try ... catch`. That's why they have the `success` property.

Comment (eliperelman) [reply packages/jest/src/index.js]: OK, so we will need to manually throw or reject or whatever. Gotcha.

Comment (okonet) [reply packages/jest/src/index.js]: Yeah. The implementation I've submitted in this PR works in my repository. I dunno why are tests failing, though.

Comment (eliperelman) [reply packages/jest/src/index.js]: OK, I'll see if I can clone locally and replicate.

Comment (eliperelman) [reply packages/jest/src/index.js]: If you make this change, I will get it out in a patch release today. :)

Comment (okonet) [reply packages/jest/src/index.js]: 🤔 why did it work for me? Did they break the API again or I’m just stupid? I’ll test the code again with different Jest versions to check that.

Comment (eliperelman) [reply packages/jest/src/index.js]: So, the just tests pass, the only thing was we were using the results properties from jest to determine pass or fail incorrectly, hence why it was failing our tests.

Comment (okonet) [reply packages/jest/src/index.js]: No, I mean I tried this fix on my project and it fixed the issue. That's why I submitted the fix in the first place.

Comment (eliperelman) [reply packages/jest/src/index.js]: Hmm not sure. You did fix the fact that it should be a promise now, so maybe that was part of it.

**Comment by okonet** [comment]
You decided to go with it? I’m sorry I still didn’t have time to investigate it
